package mapping;
// Generated 17 dic 2021 10:41:17 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private Date fecha;
	private Estaciones estaciones;
	private Date hora;
	private float comgm3;
	private float co8hmgm3;
	private int nogm3;
	private int no2;
	private String no2ica;
	private int noxgm3;
	private float pm10;
	private String pm10ica;
	private float pm25;
	private String pm25ica;
	private int so2;
	private String so2ica;
	private String icaestacion;

	public Datos() {
	}

	public Datos(Date fecha, Estaciones estaciones, Date hora, float comgm3, float co8hmgm3, int nogm3, int no2,
			String no2ica, int noxgm3, float pm10, String pm10ica, float pm25, String pm25ica, int so2, String so2ica,
			String icaestacion) {
		this.fecha = fecha;
		this.estaciones = estaciones;
		this.hora = hora;
		this.comgm3 = comgm3;
		this.co8hmgm3 = co8hmgm3;
		this.nogm3 = nogm3;
		this.no2 = no2;
		this.no2ica = no2ica;
		this.noxgm3 = noxgm3;
		this.pm10 = pm10;
		this.pm10ica = pm10ica;
		this.pm25 = pm25;
		this.pm25ica = pm25ica;
		this.so2 = so2;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Estaciones getEstaciones() {
		return this.estaciones;
	}

	public void setEstaciones(Estaciones estaciones) {
		this.estaciones = estaciones;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public float getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(float comgm3) {
		this.comgm3 = comgm3;
	}

	public float getCo8hmgm3() {
		return this.co8hmgm3;
	}

	public void setCo8hmgm3(float co8hmgm3) {
		this.co8hmgm3 = co8hmgm3;
	}

	public int getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(int nogm3) {
		this.nogm3 = nogm3;
	}

	public int getNo2() {
		return this.no2;
	}

	public void setNo2(int no2) {
		this.no2 = no2;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public int getNoxgm3() {
		return this.noxgm3;
	}

	public void setNoxgm3(int noxgm3) {
		this.noxgm3 = noxgm3;
	}

	public float getPm10() {
		return this.pm10;
	}

	public void setPm10(float pm10) {
		this.pm10 = pm10;
	}

	public String getPm10ica() {
		return this.pm10ica;
	}

	public void setPm10ica(String pm10ica) {
		this.pm10ica = pm10ica;
	}

	public float getPm25() {
		return this.pm25;
	}

	public void setPm25(float pm25) {
		this.pm25 = pm25;
	}

	public String getPm25ica() {
		return this.pm25ica;
	}

	public void setPm25ica(String pm25ica) {
		this.pm25ica = pm25ica;
	}

	public int getSo2() {
		return this.so2;
	}

	public void setSo2(int so2) {
		this.so2 = so2;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

}
