package mapping;
// Generated 20 dic 2021 20:57:13 by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Datos generated by hbm2java
 */
public class Datos implements java.io.Serializable {

	private Date fecha;
	private Date hora;
	private float comgm3;
	private int nogm3;
	private int no2;
	private String no2ica;
	private float pm10;
	private float pm25;
	private int so2;
	private String so2ica;
	private String icaestacion;
	private int idestacion;

	public Datos() {
	}

	public Datos(Date fecha, Date hora, float comgm3, int nogm3, int no2, String no2ica, float pm10, float pm25,
			int so2, String so2ica, String icaestacion, int idestacion) {
		this.fecha = fecha;
		this.hora = hora;
		this.comgm3 = comgm3;
		this.nogm3 = nogm3;
		this.no2 = no2;
		this.no2ica = no2ica;
		this.pm10 = pm10;
		this.pm25 = pm25;
		this.so2 = so2;
		this.so2ica = so2ica;
		this.icaestacion = icaestacion;
		this.idestacion = idestacion;
	}

	public Date getFecha() {
		return this.fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Date getHora() {
		return this.hora;
	}

	public void setHora(Date hora) {
		this.hora = hora;
	}

	public float getComgm3() {
		return this.comgm3;
	}

	public void setComgm3(float comgm3) {
		this.comgm3 = comgm3;
	}

	public int getNogm3() {
		return this.nogm3;
	}

	public void setNogm3(int nogm3) {
		this.nogm3 = nogm3;
	}

	public int getNo2() {
		return this.no2;
	}

	public void setNo2(int no2) {
		this.no2 = no2;
	}

	public String getNo2ica() {
		return this.no2ica;
	}

	public void setNo2ica(String no2ica) {
		this.no2ica = no2ica;
	}

	public float getPm10() {
		return this.pm10;
	}

	public void setPm10(float pm10) {
		this.pm10 = pm10;
	}

	public float getPm25() {
		return this.pm25;
	}

	public void setPm25(float pm25) {
		this.pm25 = pm25;
	}

	public int getSo2() {
		return this.so2;
	}

	public void setSo2(int so2) {
		this.so2 = so2;
	}

	public String getSo2ica() {
		return this.so2ica;
	}

	public void setSo2ica(String so2ica) {
		this.so2ica = so2ica;
	}

	public String getIcaestacion() {
		return this.icaestacion;
	}

	public void setIcaestacion(String icaestacion) {
		this.icaestacion = icaestacion;
	}

	public int getIdestacion() {
		return this.idestacion;
	}

	public void setIdestacion(int idestacion) {
		this.idestacion = idestacion;
	}

}
