package mapping;
// Generated 20 dic 2021 20:57:13 by Hibernate Tools 5.5.7.Final

/**
 * Estaciones generated by hbm2java
 */
public class Estaciones implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String provincia;
	private String direcion;
	private float coordX;
	private float coordY;
	private float latitud;
	private float longitud;
	private int idPueblo;

	public Estaciones() {
	}

	public Estaciones(String nombre, String provincia, String direcion, float coordX, float coordY, float latitud,
			float longitud, int idPueblo) {
		this.nombre = nombre;
		this.provincia = provincia;
		this.direcion = direcion;
		this.coordX = coordX;
		this.coordY = coordY;
		this.latitud = latitud;
		this.longitud = longitud;
		this.idPueblo = idPueblo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getProvincia() {
		return this.provincia;
	}

	public void setProvincia(String provincia) {
		this.provincia = provincia;
	}

	public String getDirecion() {
		return this.direcion;
	}

	public void setDirecion(String direcion) {
		this.direcion = direcion;
	}

	public float getCoordX() {
		return this.coordX;
	}

	public void setCoordX(float coordX) {
		this.coordX = coordX;
	}

	public float getCoordY() {
		return this.coordY;
	}

	public void setCoordY(float coordY) {
		this.coordY = coordY;
	}

	public float getLatitud() {
		return this.latitud;
	}

	public void setLatitud(float latitud) {
		this.latitud = latitud;
	}

	public float getLongitud() {
		return this.longitud;
	}

	public void setLongitud(float longitud) {
		this.longitud = longitud;
	}

	public int getIdPueblo() {
		return this.idPueblo;
	}

	public void setIdPueblo(int idPueblo) {
		this.idPueblo = idPueblo;
	}

}
