package mapping;
// Generated 20 dic 2021 20:57:13 by Hibernate Tools 5.5.7.Final

/**
 * Favoritos generated by hbm2java
 */
public class Favoritos implements java.io.Serializable {

	private Integer id;
	private String usuario;
	private Integer idPueblo;
	private Integer idLugar;

	public Favoritos() {
	}

	public Favoritos(String usuario) {
		this.usuario = usuario;
	}

	public Favoritos(String usuario, Integer idPueblo, Integer idLugar) {
		this.usuario = usuario;
		this.idPueblo = idPueblo;
		this.idLugar = idLugar;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public Integer getIdPueblo() {
		return this.idPueblo;
	}

	public void setIdPueblo(Integer idPueblo) {
		this.idPueblo = idPueblo;
	}

	public Integer getIdLugar() {
		return this.idLugar;
	}

	public void setIdLugar(Integer idLugar) {
		this.idLugar = idLugar;
	}

}
