package mapping;
// Generated 17 dic 2021 10:41:17 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Favoritos generated by hbm2java
 */
public class Favoritos implements java.io.Serializable {

	private Integer id;
	private Usuarios usuarios;
	private String nombreLugar;
	private Set lugareses = new HashSet(0);

	public Favoritos() {
	}

	public Favoritos(Usuarios usuarios, String nombreLugar) {
		this.usuarios = usuarios;
		this.nombreLugar = nombreLugar;
	}

	public Favoritos(Usuarios usuarios, String nombreLugar, Set lugareses) {
		this.usuarios = usuarios;
		this.nombreLugar = nombreLugar;
		this.lugareses = lugareses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Usuarios getUsuarios() {
		return this.usuarios;
	}

	public void setUsuarios(Usuarios usuarios) {
		this.usuarios = usuarios;
	}

	public String getNombreLugar() {
		return this.nombreLugar;
	}

	public void setNombreLugar(String nombreLugar) {
		this.nombreLugar = nombreLugar;
	}

	public Set getLugareses() {
		return this.lugareses;
	}

	public void setLugareses(Set lugareses) {
		this.lugareses = lugareses;
	}

}
