package mapping;
// Generated 17 dic 2021 9:57:51 by Hibernate Tools 5.5.7.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios implements java.io.Serializable {

	private String usuario;
	private String contraseña;
	private Set favoritoses = new HashSet(0);
	private Set galerias = new HashSet(0);

	public Usuarios() {
	}

	public Usuarios(String usuario, String contraseña) {
		this.usuario = usuario;
		this.contraseña = contraseña;
	}

	public Usuarios(String usuario, String contraseña, Set favoritoses, Set galerias) {
		this.usuario = usuario;
		this.contraseña = contraseña;
		this.favoritoses = favoritoses;
		this.galerias = galerias;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContraseña() {
		return this.contraseña;
	}

	public void setContraseña(String contraseña) {
		this.contraseña = contraseña;
	}

	public Set getFavoritoses() {
		return this.favoritoses;
	}

	public void setFavoritoses(Set favoritoses) {
		this.favoritoses = favoritoses;
	}

	public Set getGalerias() {
		return this.galerias;
	}

	public void setGalerias(Set galerias) {
		this.galerias = galerias;
	}

}
